import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Montserrat } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import NextTopLoader from "nextjs-toploader";

import { getCurrentUser } from "@/lib/dal/user";
import { NotificationProvider } from "@/context/NotificationContext";
import { Suspense } from "react";
import UserSessionFetcher from "@/components/Shared/UserSessionFetcher";
// import { ThemeProvider } from "@/components/theme-provider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "prolancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userPromise = getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <NextTopLoader color="#10B981" showSpinner={false} />
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        </ThemeProvider> */}
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <NotificationProvider initialUser={null}>
          <Suspense fallback={null}>
            <UserSessionFetcher userPromise={userPromise} />
          </Suspense>
          {children}
        </NotificationProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
